### PR TITLE
[ WIP ] Upstream Merge F7 Improvements by DieHertz

### PR DESCRIPTION
**Pull request by kidBrazil**
DieHertz has done some amazing work optimizing F7's - this PR is intended to get those merged into Butterflight so our F7 users can also use the features.

- TODO - Fix compile error on F7 targets, likely missing code from a previous merge or change.

### CODE REVIEW

**Comment by sUbLiMe-FPV** [comment]
Yo Brah!

Any updatez on this?!! I just got a omnibusf7 and I want to slather the butta on it!  ;)

**Comment by kidBrazil** [comment]
@sUbLiMe-FPV Haven't had a chance to work on this since I opened it. I have 3 client deadlines coinciding at my agency so it's been all hands on deck. Will get back to it soon =)

**Comment by sUbLiMe-FPV** [comment]
Awesome man!! So pumped!!  I don't know what a diehertz is or where to get one but I'm all in for testing omnibusf7.

**Comment by MikeCHunt** [comment]
I just got my first flight controller and I love it! I would really like to help out this project so can you tell me where to get started with the code? I need some guidance from the skilled programmers already working on the project. I have lots of experience in html and javascript so I should be able to help. I've even built my own websites from scratch! I'm looking at the code and I don't see how the main page is loaded so need help getting started.

**Comment by kidBrazil** [comment]
@MikeCHunt - Hey man, I really appreciate your enthusiasm and your desire to help, however I think your particular set of skills would be better suited for helping us over on the configurator. Take a look at the codebase here https://github.com/butterflight/butterflight-configurator

**Comment by MikeCHunt** [comment]
@kidBrazil Thanks, but I really want to work on the firmware and help get this working. My long term plan is to build my own flight controller and I was hoping to use F7. What skills do you think I need to help figure this out? Seems like there is a lot of code here that's difficult to understand.

**Comment by MikeCHunt** [comment]
@sUbLiMe-FPV Did you ever figure out where to get a diehertz board? I'll buy one if it helps the development.

**Comment by sUbLiMe-FPV** [comment]
No man.  I googled but couldn't find anything.  Must be a prototype or something.  I only have omnibusf7.  Good luck with your own design and let me know if you need help testing!

**Comment by sUbLiMe-FPV** [comment]
@kidBrazil Any updates on this brah?  I tried running my omnibusf7 on Butterflight but I can't run 32k because the cpu goes to 100%. I tested on Betaflight and it works perfectly and only uses about 20% cpu. But man I want some butter!

**Comment by sUbLiMe-FPV** [comment]
@livid-fpv I don't understand what you mean man. What's a mess? Like I said, I tested in Betaflight 3.4 and it worked great! Running 32/32 with dshot1200. But I want to butter it up.

**Comment by livid-fpv** [comment]
ATM It doesn't fly any better, and you have a lot of issues with dshot and 32k. the blheli32 devs themselves admit that dshot1200 cannot handle 32k, there is noticeable packet loss, multishot is still the best for 32k

**Comment by sUbLiMe-FPV** [comment]
I don't understand - what doesn't fly better? I thought 32k was where it's at and the reason Butterflight is so smooth and buttery! Also I thought you can't do turtle mode with multishot?

**Comment by livid-fpv** [comment]
Butter's magic comes mainly from the kalman filter, 32k doesn't present an
advantage yet over 8k, it introduces noise issues that aren't there on 8k,
and yes, no turtle mode on MS, but it doesn't suffer from packet loss like
dshot. proshot1000 may present the best of both worlds, not enough testing
has been done yet

**Comment by kidBrazil** [comment]
Closing since there is already a Rebase PR in the works.

**Pull request closed without merging**
