### PR TITLE
Setting FKF As default with better values & removing TAZ

### PR DESCRIPTION
**Pull request by kidBrazil**
Made FKF the default, so we can stop fielding so many questions as to how to enable it. People are coming to this FW because they want to use FKF so we might as well provide it as default.

* Added default Q and R values - can be tweaked
* Disabled notch 1 & 2
* Lowered stock D Gain a little bit since it seems to give folks grief and 35 is way too high.
* Disabled Gyro Overflow - seems to cause issues on 32khz
* Disabled anti-taz until we get it out of here

### CODE REVIEW

**Comment by livid-fpv** [comment]
Why remove anti taz?

**Comment by lunohod** [comment]
Why do you remove anti-taz?

**Comment by kidBrazil** [comment]
@livid-fpv @lunohod - I don't trust the current implementation, seems to be causing trouble for some users.

Furthermore, the feature doesn't actually prevent injury and I believe would give users a false sense of safety.

**Comment by lunohod** [comment]
I read one guy actually avoided injuries thanks to that feature. Maybe it's time to open a safer-butter-flight fork.

**Comment by kidBrazil** [comment]
@lunohod Indeed, I have read that too - but I have also read many quads disarming and having issues. So we are disabling it for now until that can be fixed. Or at least that is the proposal on this PR.

**Comment by hsuq510** [comment]
400/88 default value are for 8/8 or 32/16 ?

**Comment by kidBrazil** [comment]
@hsuq510 8/8khz

**Pull request merged**
