### PR TITLE
solve numeric issues with jitter on the time axis.

### PR DESCRIPTION
**Pull request by robert-b**

### CODE REVIEW

**Comment by kidBrazil** [comment]
@robert-b Hey man, would you mind adding descriptions to your Pull requests? Doesnt have to be much but context is always helpful.

Also.. build is currently failing with Jenkins.

Cheers

**Comment by robert-b** [comment]
Control applications demand the use of strict timing constraints. The used scheduling methods introduce jitter on task executions. This implies that the separation between consecutive starting times of a given control task is not constant. In the same time control theory assumes that sampling periods were constant. These variations on the sampling period of control task implementation can degrade the control system performance and in ultimately can induce instability in the system.

**Comment by robert-b** [comment]
the compile problems are not related to my changes.
locally it can be compiled.

**Comment by kidBrazil** [comment]
@robert-b thanks! I will take a look at the compile issue.

**Comment by robert-b** [comment]
i did confuse git with a simple rename of the repo.
will resend the pr on the normal name.

**Pull request closed without merging**
