### PR TITLE
Add new target SPEEDYBEEF4

### PR DESCRIPTION
**Pull request by allenfor2017**
Hi~
I added a new target for SPEEDYBEEF4, please review! Thank you!

### CODE REVIEW

**Comment by allenfor2017** [comment]
Hi~
@kidBrazil, don't merge my code for the time being, I still have a parameter that needs testing to confirm! Thank you

**Comment by kidBrazil** [comment]
@allenfor2017 Any updates on this?

**Comment by allenfor2017** [comment]
HI~@kidBrazil
My new SpeedyBee F4 target has been merged, so please review it.THANKS

**Comment by allenfor2017** [comment]
@kidBrazil
Hi~  
Is the current request still going on?

**Pull request merged**
