### PR TITLE
HELIOSPRING attitude correction (compute quaternion helper products)

### LINKED ISSUE #116: RC7-Caprica HELIOSPRING HEADADJ broken
In  HEADFREE mode ,
HEADADJ  (adjusting for new heading)
does not work.

### PR DESCRIPTION
**Pull request by adrianmiriuta**
HELIOSPRING
attitude correction (compute quaternion helper products)
fix #116 HEADADJ (hope , cannot test).

### CODE REVIEW

**Comment by orneryd** [comment]
i think it needs to be be like this:

``` 
#ifndef USE_GYRO_IMUF9001
    quaternion vError = VECTOR_INITIALIZE;
    quaternion vGyroAverage;
    gyroGetAverage(&vGyroAverage);

    quaternion vAccAverage;
    if (accGetAverage(&vAccAverage) && accIsHealthy(&vAccAverage)) {
        applyAccError(&vAccAverage, &vError);
    }
    DEBUG_SET(DEBUG_IMU, DEBUG_IMU_VACCMODULUS, lrintf((quaternionModulus(&vAccAverage)/ acc.dev.acc_1G) * 1000));
    imuMahonyAHRSupdate(deltaT * 1e-6f, &vGyroAverage, &vError);    
    applySensorCorrection(&vError);
#else
    UNUSED(deltaT);
    UNUSED(applyAccError);
    UNUSED(imuMahonyAHRSupdate);
    qAttitude.w = imufQuat.w;
    qAttitude.x = imufQuat.x;
    qAttitude.y = imufQuat.y;
    qAttitude.z = imufQuat.z;
    quaternionComputeProducts(&qAttitude, &qpAttitude);   
    applySensorCorrection(&qAttitude);
#endif
    imuUpdateEulerAngles();
#endif
```

because the imuMahonyAHRSupdate call happens separately and that call is made when calculating ACC

**Comment by orneryd** [comment]
Thank you @adrianmiriuta! I combined this into #118

**Comment by kidBrazil** [comment]
Included in #118 - Thanks @adrianmiriuta !

**Comment by adrianmiriuta** [comment]
@orneryd 
yes this is better !

**Pull request closed without merging**
