### PR TITLE
adding helio to skip_targets

### PR DESCRIPTION
**Pull request by orneryd**
This will prevent the non-aggregates from showing up in the UI

### CODE REVIEW

**Comment by brucesdad13** [comment]
Glad to see SKIP_TARGETS getting some use 😁

**Comment by kidBrazil** [comment]
image

Travis seems to be having some issues.

**Comment by kidBrazil** [comment]
@orneryd Whats going on with this PR? Been sitting a while, do we still need this?

**Comment by orneryd** [comment]
I changed this differently int he configurator

**Pull request closed without merging**
