### PR TITLE
Updated ALIENWHOOP defaults for Butterflight; added Blackbox

### PR DESCRIPTION
**Pull request by brucesdad13**
Redo of PR #172

### CODE REVIEW

**Comment by brucesdad13** [comment]
@kidBrazil is Travis CI dead? 😬

**Comment by kidBrazil** [comment]
@brucesdad13 I told it to do it again =)

**Comment by brucesdad13** [comment]
Thanks!

**Comment by brucesdad13** [comment]
image
Waiting for merge ;D

**Pull request merged**
