### PR TITLE
Setting FKF As default with better values & removing TAZ

### PR DESCRIPTION
**Pull request by kidBrazil**
Made FKF the default, so we can stop fielding so many questions as to how to enable it. People are coming to this FW because they want to use FKF so we might as well provide it as default.

* Added default Q and R values - can be tweaked
* Disabled notch 1 & 2
* Lowered stock D Gain a little bit since it seems to give folks grief and 35 is way too high.
* Disabled Gyro Overflow - seems to cause issues on 32khz
* Disabled anti-taz until we get it out of here

### CODE REVIEW

**Comment by loomerco** [comment]
Why get Anti - Taz out?

**Comment by chriswils** [comment]
Because people have experienced random disarms after takeoff, making this quite a scary feature (bf did not test this properly out with pilots before going for it)

**Comment by loomerco** [comment]
Well I have also seen more than one guy who was saved by this feature.

Why not just improve/fix it instead of taking it out? many newbies are using this firmware and we all make mistakes.
I would rather have unintentional disarms here and there and not have myself, or any of the other guys, hurt himself due to a code mistake (happened for example when gyro was turned 90 degrees on a new release for one of the builds) or a setup mistake.

Besides - it is tuneable.

**Comment by chriswils** [comment]
Why are newbies using this firmware? It's the most mainstream experimental thing you can find. 

I think they are working in a fix, and in the meantime disabling it. We managed just fine for quite some time without it. I would rather not punch the throttle and have it freefall due to an unwanted disarm, than have a feature that is unnecessary if you have your props right (which always should be checked). 

How tunable? Will a newbie be comfortable and knowledgeable enough to tune it themselves?

I see your point, but if you have seen several guys been saved by this (instead of having the disarm ready to go), I guess they are beginners, and should really go with betaflight to start off with. Then, when comfortable, move into experimental releases like BuF. Just my opinion

**Comment by loomerco** [comment]
Because there great hipe around the FKF and that’s the only firmware giving access to it for now. I was the first in my area to try it but since about 2 weeks ago everybody around me has started moving to butterflight.

What you wrote regarding newbies might be right but none of us have control over who uses it or not and it’s out there for all.

I would be ok to have it disabled until fixed but that’s not what is written at the top of this discussion: it says disable until moved out.

**Pull request closed without merging**
