### PR TITLE
Buttered up README.MD and get rid of "Feature Freeze"

### PR DESCRIPTION
**Pull request by kidBrazil**
Cleaned up readme and removed the annoying feature freeze template

### CODE REVIEW

**Comment by rs2k** [comment]
WOOHOO!

**Comment by mtnmikev** [comment]
Hey guys!  Anyone having issues with the Config?  Is it ready to load?  Not working for me. THX

**Comment by kidBrazil** [comment]
@mtnmikev Hey man, it should be working if you grabbed the latest from MASTER or butterflight.co - remember you gotta grab the latest hexes from there as well.

That said, could you provide more details?

**Comment by mtnmikev** [comment]
All good! Brain fart on my end. THX

**Pull request merged**
