### PR TITLE
Kmitchel proposes merging Fujin's FKF Code into Butterflight

### PR DESCRIPTION
**Pull request by kidBrazil**

### CODE REVIEW

**Comment by apocolipse** [comment]
@kmitchel Can you add this in as separate functions instead of changing the existing filter?  As well as add an option to the stage2_filter_type enum for the CLI option and the accompanying switch case in gyro.c?  Thanks

**Comment by kmitchel** [comment]
I'll get to work.

**Comment by kmitchel** [comment]
Made requested changes.  I'll need to dbl-check and test tomorrow.  Ty

**Comment by kmitchel** [comment]
@apocolipse Please review when you have a moment. I think I have everything, but I am wondering if recylcing fastKalmanApplyFn is ok.

**Comment by apocolipse** [comment]
@kmitchel i think you might need to rebase/squash again as we just fixed the bug with cpu_overclock

**Comment by kmitchel** [comment]
@apocolipse can you give me a pointer for squashing after merge...keep getting into trouble

I git fetch upstream, git pull upstream master, edit conflicts , stage and commit changes.

When I git rebase -i HEAD~2 I can't select "Merge conflict fix"
Not sure where I keep failing.  TY

**Comment by apocolipse** [comment]
@kmitchel just re-branch off of master and push to your fork with `git push myforkname +branch_name`  note the + to force push, that'll update the PR if you force to this branch

**Comment by apocolipse** [comment]
@kmitchel looks like conflicts are resolved but you're still missing the call to init, look in gyro.c#659

**Comment by apocolipse** [comment]
@kmitchel still needs to be initialized in `gyroInitSensorFilters()`

**Pull request merged**
